### ISSUE TITLE
How To Edit / Update Method?

### ISSUE THREAD

**Issue by bogordesaincom** [cviebrock/eloquent-taggable#110]
Please be sure you include all the relevant information in your issue so we can help you:

![Jepretan Layar 2020-05-30 pukul 17 34 44](https://user-images.githubusercontent.com/51335197/83326222-53a2d680-a29c-11ea-9b3d-05cdc32fe21b.png)

When i Store methode is success, and add new.

But In Update Methode Add `tag_id` like `7,8,9,10`

Like This
![Jepretan Layar 2020-05-30 pukul 17 35 06](https://user-images.githubusercontent.com/51335197/83326236-7634ef80-a29c-11ea-85bd-857f695be6c9.png)
![Jepretan Layar 2020-05-30 pukul 17 35 13](https://user-images.githubusercontent.com/51335197/83326239-78974980-a29c-11ea-8946-0e98a10fae08.png)

How to Solved in Method Edit and Store.

in Edit i setup this :
```
$tags = Tag::pluck('name', 'tag_id');
```
in Store

```
$tags = $request->input('tags');
        $product->tag($tags);
```
- [ ] steps taken to reproduce your issue
- [x] your configuration file(s), where relevant
- [ ] a copy of your Models that use or extend this package (just the relevant parts!)
- [ ] any other code we might need to help

Also, *please* use [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/)
when pasting more than one line of code.  It makes it so much more readable for everyone!

**Thank you!**

**Comment by cviebrock** [comment]
Sorry for the delay.

I'm not sure I understand the issue.  `$product->tag($tags)` treats `$tags` as a comma-delimited string of the actual tags you want to add.  In your case, you are asking it to tag the product with the strings "7", "8", "9", etc..

I suspect that "7" is really the id of an existing tag you want to add to the product, yes?  I would see if you could update your front end to return the tag _names_ instead of the tag _ids_ you want to add to the models.  Then your controller code should work as-is.  If you can only return the ids, then you'd need to look up the tags with those ids and tag the models that way.  e.g. something like this (untested):

```php
$tagIds = $request->input('tags');
$tagNames = Tag::whereIn('id', explode(',', $tagIds)->get()
    ->pluck('name')->all();
$product->tag($tagNames);
```

It's not that pretty, I agree.  I will make a note to add a `tagById()` method in the next version.

**Comment by cviebrock** [comment]
I forgot to mention this, but `tagById()`, `untagById()`, and `retagById()` now exist in the latest version of the package.
